### PR TITLE
Added a converter for rocker switch action to dimmer item.

### PR DESCRIPTION
**Pull request by kungfoolfighting**
This will allow rocker switched to be paired with dimmer items and enable short-press on/off and long-press dimming without setting any CONVPARAM.

I am not sure how to handle the copyright stuff, since most of the new class was simply copied from your code.

### CODE REVIEW

**Comment by maggu2810** [comment]
Sorry, I reviewed the code in #13.
Perhaps you could implement that comments.

I think this is a nice feature.

**Comment by kungfoolfighting** [comment]
Yeah, my bad, I am new to GitHub and didn't exactly know how to do the whole pull request thing here.
Is there a trick to modifying the pull request so that it contains only the NPE fix? Since you already added all the comments to that other pull request, what will happen when I simply remove the head revision from my master branch?

**Comment by maggu2810** [comment]
A PR keeps track of the branch it has been created for.
So every change to your branch "RockerSwitchDimmerItem" will change this PR.
Your other PR has been created your branch "master". It is common practice not to use master to create a PR (but still okay if you do not add other changes).
Perhaps you should create a new branch for the NPE fix, close the old (that is using master) and create a new PR using the new branch with the only one commit.

Then you could integrate the comments mentioned in #13 into this branch.

**Comment by kungfoolfighting** [comment]
Done.

**Comment by maggu2810** [comment]
NPE fix has been merged, but it seems you have not integrated the comments into this branch / PR.

**Comment by kungfoolfighting** [comment]
No, not yet, will get to it sometime today and then I will commit a new patch to this branch.

**Comment by kungfoolfighting** [comment]
Okay, I progressed a bit. I am having problems with the ESH scheduler though.

I checked the GitHub repo for ESH and searched for scheduler, but could only find a scheduler bundle that I don't really know if it is what I am supposed to use.

If you are not talking about a specific type in the ESH implementation, that I am supposed to use but rather a scheduler instance, which I should use, then I am also not sure how to get that instance. 

I understand that the point is to reuse a global(?) ESH scheduler so as not to create too many independent scheduler threads, but I don't know the ESH architecture at all, so I am pretty stuck here.

**Comment by maggu2810** [comment]
It is okay, if you add

```java
// TODO: use ESH scheduler
 private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
```

I will have a look at (some time).

**Comment by kungfoolfighting** [comment]
I don't know if GitHub notifies you about new commits to pull requests, so I am just leaving this comment here to make sure.

**Comment by maggu2810** [comment]
Github sends no notification, so thanks for your comment.

I realized that there are different authors of the commits, has this been done by intention?

I would prefer if you sign-off your commits (common practice for commits). Can you do so.

If you sign off your commits you could also squash the commits.

If you need some further help, feel free to contact me directly.

**Comment by kungfoolfighting** [comment]
I just had a different identity set on another computer, so that's why it says it's different identities.

I have squashed and signed off on the commit. I hope that is what you meant by signing off on it.

**Comment by maggu2810** [comment]
All fine, thank you.

**Pull request merged**
